//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Animals.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Animals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _27e6b021_fba6_43a9_961e_0d8957ccdade {
            get {
                object obj = ResourceManager.GetObject("27e6b021-fba6-43a9-961e-0d8957ccdade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7df0132c_8730_4b61_83d9_ad33cf293e30 {
            get {
                object obj = ResourceManager.GetObject("7df0132c-8730-4b61-83d9-ad33cf293e30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7df0132c_8730_4b61_83d9_ad33cf293e301 {
            get {
                object obj = ResourceManager.GetObject("7df0132c-8730-4b61-83d9-ad33cf293e301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _92e40310_3357_4ca2_be61_61ff09cbbe60 {
            get {
                object obj = ResourceManager.GetObject("92e40310-3357-4ca2-be61-61ff09cbbe60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_10_17_at_13_39_30_b236c59c {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-10-17 at 13.39.30_b236c59c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_10_21_at_00_51_24_526f3adf {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-10-21 at 00.51.24_526f3adf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_10_21_at_01_16_19_e3d67c8c {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-10-21 at 01.16.19_e3d67c8c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_01_at_19_54_10_6c8b8675 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-01 at 19.54.10_6c8b8675", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_01_at_19_54_11_9666c298 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-01 at 19.54.11_9666c298", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_01_at_19_54_14_9c45d716 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-01 at 19.54.14_9c45d716", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_01_at_19_54_28_9601a985 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-01 at 19.54.28_9601a985", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_01_at_20_47_18_c54c56e9 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-01 at 20.47.18_c54c56e9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_01_at_20_47_22_689635e7 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-01 at 20.47.22_689635e7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_01_at_23_42_32_911e46c3 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-01 at 23.42.32_911e46c3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_01_at_23_49_08_3f6df5f5 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-01 at 23.49.08_3f6df5f5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_03_at_22_03_44_864b193c {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-03 at 22.03.44_864b193c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_15_45_29956c2d {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.15.45_29956c2d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_15_47_13a3fe23 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.15.47_13a3fe23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_15_47_42a4dbd5qq {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.15.47_42a4dbd5qq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_15_47_8920be43 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.15.47_8920be43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_15_48_5c9876d4 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.15.48_5c9876d4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_15_49_0d221225 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.15.49_0d221225", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_15_49_fe4ca9a6 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.15.49_fe4ca9a6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_15_50_25537088 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.15.50_25537088", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_15_50_b0561932 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.15.50_b0561932", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_151 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_152 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.152", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_153 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.153", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_154 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.154", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_155 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.155", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_52_42_b5397f27 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.52.42_b5397f27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_16_52_44_a719d1b5qq {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 16.52.44_a719d1b5qq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_17_43_26_e2168dbaqq {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at 17.43.26_e2168dbaqq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_05_at_qqqq {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-05 at qqqq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_06_at_00_54_42_5704396d {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-06 at 00.54.42_5704396d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_06_at_00_54_42_d4a3a739 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-06 at 00.54.42_d4a3a739", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2024_11_06_at_00_54_44_0d32433a {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-11-06 at 00.54.44_0d32433a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
